spring: 
 datasource:
  url: jdbc:mysql://localhost:3306/assignment
  username: root
  password: root@root
  driver-class-name: com.mysql.cj.jdbc.Driver
 jpa:
    hibernate:
      ddl-auto: update  # or create, create-drop, validate depending on your needs
    show-sql: true
    properties:
      hibernate:
        format_sql: true			
